#docker-compose.yml
services:
  mongo:
    image: mongo:latest
    container_name: noscites-solo
    networks:
      - noscites-net
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_NAME: noscites                
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: 
networks:
  noscites-net:
    driver: bridge